#!/usr/bin/env python3
"""
Import expanded knowledge base data into nodes.json / edges.json.

Reads existing data generated by parse_vocab.py, then adds:
  1. L2 inference results (ingredient_relations, ingredient_efficacy, ingredient_risk, ingredient_tolerance)
  2. L2 auto-generated risk_for relationships (1,170 rows)
  3. L5 synonym pairs from normalization work (7 dimension TSV files)
"""
import csv
import json
import re
from pathlib import Path
from collections import Counter

# Paths
DATA_DIR = Path("/Users/sunzhuoqi/Desktop/skincare-kg-platform/frontend/src/data")
EXPANDED_DIR = Path("/Users/sunzhuoqi/Desktop/成分关系推断结果")

# Load existing data
with open(DATA_DIR / "nodes.json", "r", encoding="utf-8") as f:
    nodes = json.load(f)
with open(DATA_DIR / "edges.json", "r", encoding="utf-8") as f:
    edges = json.load(f)

node_ids = {n["id"]: n for n in nodes}
edge_counter = [len(edges)]

# Chinese-name → existing node ID lookup for ingredients
ingredient_cn_to_id = {}
for n in nodes:
    d = n["data"]
    if d["entityType"] == "Ingredient" and d["layer"] == "L2":
        ingredient_cn_to_id[d["label"]] = n["id"]
        # Also map aliases
        aliases = d["properties"].get("aliases", [])
        if isinstance(aliases, list):
            for a in aliases:
                ingredient_cn_to_id[a] = n["id"]

# Skin type label → code mapping
skin_target_map = {
    "sensitive": "sensitive", "敏感肌": "sensitive",
    "pregnant": "pregnant", "孕妇": "pregnant",
    "acne_prone": "acne_prone", "痘痘肌": "acne_prone",
    "dry": "dry", "干皮": "dry", "干性": "dry",
    "oily": "oily", "油皮": "oily",
    "breastfeeding": "breastfeeding", "哺乳期": "breastfeeding",
}

# Efficacy label → code mapping
efficacy_cn_to_id = {}
for n in nodes:
    d = n["data"]
    if d["entityType"] == "Efficacy" and d["layer"] == "L2":
        efficacy_cn_to_id[d["label"]] = n["id"]


def sanitize_code(name):
    """Convert Chinese name to a safe ID code."""
    return re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff]", "_", name).strip("_")


def make_id(layer, etype, code):
    return f"{layer}_{etype}_{code}"


def add_node(layer, etype, code, label, labelEn="", **props):
    nid = make_id(layer, etype, code)
    if nid in node_ids:
        return nid
    node = {
        "id": nid,
        "data": {
            "label": label,
            "labelEn": labelEn,
            "layer": layer,
            "entityType": etype,
            "properties": {"code": code, **{k: v for k, v in props.items() if v is not None and v != ""}}
        }
    }
    nodes.append(node)
    node_ids[nid] = node
    return nid


def add_edge(src, tgt, relType, category, label, **props):
    if src not in node_ids or tgt not in node_ids:
        return False
    edge_counter[0] += 1
    edges.append({
        "id": f"edge_{edge_counter[0]:04d}",
        "source": src,
        "target": tgt,
        "data": {
            "relType": relType,
            "category": category,
            "label": label,
            "properties": {k: v for k, v in props.items() if v is not None and v != ""}
        }
    })
    return True


def load_tsv(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            rows.append(row)
    return rows


# ================================================================
# 1. Import L2 inference results
# ================================================================
def import_l2_inference():
    """Import batch1 inference results: relations, efficacy, risk, tolerance."""
    stats = {"relations": 0, "efficacy": 0, "risk": 0, "tolerance": 0}

    # 1a. ingredient_relations.tsv (conflicts_with / synergizes_with)
    path = EXPANDED_DIR / "ingredient_relations.tsv"
    if path.exists():
        for row in load_tsv(path):
            from_name = row["from_ingredient"]
            to_name = row["to_ingredient"]
            relation = row["relation"]
            # Create ingredient nodes if not existing
            from_code = sanitize_code(from_name)
            to_code = sanitize_code(to_name)
            from_id = ingredient_cn_to_id.get(from_name) or add_node("L2", "Ingredient", from_code, from_name)
            to_id = ingredient_cn_to_id.get(to_name) or add_node("L2", "Ingredient", to_code, to_name)

            if relation == "conflicts_with":
                cat, lbl = "互斥约束", "冲突"
            else:
                cat, lbl = "协同增强", "协同"

            added = add_edge(from_id, to_id, relation, cat, lbl,
                             confidence=row.get("confidence", ""),
                             constraint_type=row.get("constraint_type", ""),
                             interval=row.get("interval", ""),
                             condition=row.get("condition", ""),
                             evidence=row.get("evidence", ""))
            if added:
                stats["relations"] += 1

    # 1b. ingredient_efficacy.tsv
    path = EXPANDED_DIR / "ingredient_efficacy.tsv"
    if path.exists():
        for row in load_tsv(path):
            ing_name = row["ingredient"]
            ing_code = sanitize_code(ing_name)
            ing_id = ingredient_cn_to_id.get(ing_name) or add_node("L2", "Ingredient", ing_code, ing_name)

            primary = row.get("primary_efficacy", "")
            all_effs = row.get("all_efficacies", "")
            confidence = row.get("confidence", "")

            # Create efficacy nodes for each listed efficacy
            for eff in all_effs.split(";"):
                eff = eff.strip()
                if not eff:
                    continue
                eff_code = sanitize_code(eff)
                eff_id = efficacy_cn_to_id.get(eff) or add_node("L2", "Efficacy", eff_code, eff)
                is_primary = "primary" if eff == primary else "secondary"
                added = add_edge(ing_id, eff_id, "has_efficacy", "因果归因", "功效",
                                 strength=is_primary, confidence=confidence)
                if added:
                    stats["efficacy"] += 1

    # 1c. ingredient_risk.tsv
    path = EXPANDED_DIR / "ingredient_risk.tsv"
    if path.exists():
        for row in load_tsv(path):
            ing_name = row["ingredient"]
            target = row["target_audience"]
            ing_code = sanitize_code(ing_name)
            ing_id = ingredient_cn_to_id.get(ing_name) or add_node("L2", "Ingredient", ing_code, ing_name)

            # Map target to skin type
            skin_code = skin_target_map.get(target, sanitize_code(target))
            # Ensure skin type node exists
            skin_id = make_id("L0", "SkinType", skin_code)
            if skin_id not in node_ids:
                add_node("L0", "SkinType", skin_code, target)

            added = add_edge(ing_id, skin_id, "risk_for", "互斥约束", "风险",
                             confidence=row.get("confidence", ""),
                             constraint_type=row.get("constraint_type", ""),
                             condition=row.get("condition", ""),
                             evidence=row.get("evidence", ""))
            if added:
                stats["risk"] += 1

    # 1d. ingredient_tolerance.tsv
    path = EXPANDED_DIR / "ingredient_tolerance.tsv"
    if path.exists():
        for row in load_tsv(path):
            ing_name = row["ingredient"]
            ing_code = sanitize_code(ing_name)
            ing_id = ingredient_cn_to_id.get(ing_name) or add_node("L2", "Ingredient", ing_code, ing_name)

            added = add_edge(ing_id, ing_id, "requires_tolerance", "互斥约束", "耐受",
                             confidence=row.get("confidence", ""),
                             interval=row.get("interval", ""),
                             condition=row.get("condition", ""),
                             evidence=row.get("evidence", ""))
            if added:
                stats["tolerance"] += 1

    print(f"L2 inference: relations={stats['relations']}, efficacy={stats['efficacy']}, "
          f"risk={stats['risk']}, tolerance={stats['tolerance']}")


# ================================================================
# 2. Import L2 auto-generated risk_for (1,170 rows)
# ================================================================
def import_l2_auto_risk():
    """Import auto-generated risk_for relationships from ingredient.tsv fields."""
    path = EXPANDED_DIR / "L2_risk_for_自动生成.tsv"
    if not path.exists():
        print("L2 auto risk: file not found")
        return

    rows = load_tsv(path)
    added = 0
    skipped = 0

    for row in rows:
        ing_name = row["ingredient"]
        target = row["risk_target"]
        risk_type = row["risk_type"]
        evidence = row.get("evidence", "")

        # Create ingredient node
        ing_code = sanitize_code(ing_name)
        ing_id = ingredient_cn_to_id.get(ing_name) or add_node("L2", "Ingredient", ing_code, ing_name)
        # Update lookup
        if ing_name not in ingredient_cn_to_id:
            ingredient_cn_to_id[ing_name] = ing_id

        # Map target to skin type
        skin_code = skin_target_map.get(target, sanitize_code(target))
        skin_id = make_id("L0", "SkinType", skin_code)
        if skin_id not in node_ids:
            add_node("L0", "SkinType", skin_code, target)

        ok = add_edge(ing_id, skin_id, "risk_for", "互斥约束", "风险",
                      constraint_type=risk_type, evidence=evidence)
        if ok:
            added += 1
        else:
            skipped += 1

    print(f"L2 auto risk: added={added}, skipped={skipped}")


# ================================================================
# 3. Import L5 synonym pairs from normalization work
# ================================================================
def import_l5_synonyms():
    """Import L5 synonym pairs from 7 dimension TSV files."""
    # Dimension config: (filename, layer, entityType, source_label)
    dimensions = [
        ("归一_新增同义词表_全量.tsv", "L2", "Ingredient", "ingredient"),
        ("归一_efficacy_新增同义词.tsv", "L2", "Efficacy", "efficacy"),
        ("归一_brand_新增同义词.tsv", "L1", "Brand", "brand"),
        ("归一_audience_新增同义词.tsv", "L0", "SkinType", "audience"),
        ("归一_category_新增同义词.tsv", "L0", "Concern", "category"),
        ("归一_skin_新增同义词.tsv", "L0", "SkinType", "skin"),
        ("归一_price_新增同义词.tsv", "L0", "Budget", "price"),
    ]

    total_nodes = 0
    total_edges = 0

    for filename, target_layer, target_type, dim_name in dimensions:
        path = EXPANDED_DIR / filename
        if not path.exists():
            print(f"  L5 {dim_name}: file not found")
            continue

        rows = load_tsv(path)
        # Group synonyms by canonical form
        canonical_groups = {}
        for row in rows:
            canon = row["canonical"]
            syn = row["synonym"]
            if canon not in canonical_groups:
                canonical_groups[canon] = []
            canonical_groups[canon].append(syn)

        dim_nodes = 0
        dim_edges = 0

        for canon, synonyms in canonical_groups.items():
            # Create a LexiconEntry node for this canonical form
            code = f"norm_{dim_name}_{sanitize_code(canon)}"
            nid = add_node("L5", "LexiconEntry", code, canon,
                           canonical=canon, variants=synonyms,
                           dimension=dim_name, synonym_count=len(synonyms))
            dim_nodes += 1

            # Try to find matching target node
            target_code = sanitize_code(canon)
            target_id = make_id(target_layer, target_type, target_code)

            # For ingredients, also try Chinese name lookup
            if target_layer == "L2" and target_type == "Ingredient":
                found_id = ingredient_cn_to_id.get(canon)
                if found_id:
                    target_id = found_id

            # For efficacy, try Chinese name lookup
            if target_layer == "L2" and target_type == "Efficacy":
                found_id = efficacy_cn_to_id.get(canon)
                if found_id:
                    target_id = found_id

            if target_id in node_ids:
                add_edge(nid, target_id, "maps_to", "等价映射", "映射")
                dim_edges += 1

        total_nodes += dim_nodes
        total_edges += dim_edges
        print(f"  L5 {dim_name}: {dim_nodes} canonical nodes, {dim_edges} maps_to edges, "
              f"{len(rows)} synonym pairs")

    print(f"L5 total: {total_nodes} nodes, {total_edges} edges")


# ================================================================
# Main
# ================================================================
def main():
    print("=" * 60)
    print("Importing expanded knowledge base")
    print(f"Starting: {len(nodes)} nodes, {len(edges)} edges")
    print("=" * 60)

    print("\n--- Step 1: L2 inference results ---")
    import_l2_inference()

    print("\n--- Step 2: L2 auto-generated risk_for ---")
    import_l2_auto_risk()

    print("\n--- Step 3: L5 synonym pairs ---")
    import_l5_synonyms()

    # Write output
    print("\n" + "=" * 60)
    print(f"Final: {len(nodes)} nodes, {len(edges)} edges")

    with open(DATA_DIR / "nodes.json", "w", encoding="utf-8") as f:
        json.dump(nodes, f, ensure_ascii=False, indent=2)
    with open(DATA_DIR / "edges.json", "w", encoding="utf-8") as f:
        json.dump(edges, f, ensure_ascii=False, indent=2)

    # Stats
    layer_counts = Counter(n["data"]["layer"] for n in nodes)
    type_counts = Counter(n["data"]["entityType"] for n in nodes)
    rel_counts = Counter(e["data"]["relType"] for e in edges)

    print(f"\nBy layer:")
    for layer in sorted(layer_counts.keys()):
        print(f"  {layer}: {layer_counts[layer]} nodes")
    print(f"\nBy entity type:")
    for etype in sorted(type_counts.keys()):
        print(f"  {etype}: {type_counts[etype]} nodes")
    print(f"\nBy relation type:")
    for rel in sorted(rel_counts.keys()):
        print(f"  {rel}: {rel_counts[rel]} edges")

    print(f"\nOutput: {DATA_DIR}/nodes.json, {DATA_DIR}/edges.json")


if __name__ == "__main__":
    main()
